name: Run Python Script

on: [push]

jobs:
  write-date:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }} # Explicitly set the token

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Run script
      run: |
        mkdir -p logs
        python -c "
        from datetime import datetime
        with open('results.txt', 'a+') as file_name:
            output_date = datetime.now().strftime('%Y-%m-%d %H:%M:%S.%f')
            file_name.write(f'{output_date}\n')
        "

    - name: Commit changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'jack1ryan007'
        git config --global user.email 'msamuel@duck.com'
        git add logs/results.txt
        git commit -m 'Update results.txt with new timestamp'
        git push
